apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- 192.168.1.27
controlPlaneEndpoint: "192.168.1.27:6443"
etcd:
  external:
    endpoints:
    - https://192.168.1.21:2379
    - https://192.168.1.22:2379
    - https://192.168.1.23:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 10.30.0.0/24
apiServerExtraArgs:
  apiserver-count: "3"
